# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd1e13720f7bdb7534a52086d9583a91c1c71f2dc379a52dcd63a2bcdde3c912f4260b6229c9217391392e2f649bb8b1f2f49c27a0e02b1dfc86cdaba36061d9

test:
  secret_key_base: edced1a594af07ad064f341d261efb1e45b5c5fc02fdca274b20672bf5c50a085a4cd75e417373378b1957fc2789f2b1d6510aa69cb9ca936e99e3951eca9045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
